version: '3'

services:
  react-app:
    image: react-app
    stdin_open: true
    restart: always
    stdin_open: true
    build:
      target: production
      context: .
    ports:
      - '3000:3000'
    networks:
      - diplom
  api-server:
    image: api-server
    restart: always
    build:
      context: .
    ports:
      - '5000:5000'
    networks:
      - diplom
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    build:
      context: .
    volumes:
      - ./data-node:/data/db
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    command: mongod --noauth
    networks:
      - diplom
networks:
  diplom:
    driver: bridge
volumes:
  mongo-data:
    driver: local
